## Final Project Submission

Please fill out:
* Student name: Brian Kanyenje
* Student pace: part time
* Scheduled project review date/time: 24/01/2025
* Instructor name: Veronica Isiaho
* Blog post URL:

# MICROSOFT MOVIE STUDIO INSIGHT

## Introduction

With many different companies getting into the movie industry, Microsoft has also decided to join the movement by creating its own film studio. However, asg a tech company with little to no knowledge when it comes to the film industry, Microsoft is faced with significant challenges such as: 
* identifying the types of films currently performing well
* understanding the factors that make a film successful

This project will solve these problems by analyzing the current trends in the film industry and translating those insights into tangible recommendationsi in order to make Microsoft's debut into the film industry successful. By examining what films and genres are rated higly as well as gross highly, he research will provide integral insight into the ingredients that make a film studio successful. All this tanslates to the amount of returns generated by the film studio.

The primary stakeholders of this project are the head of Microsoft's film studio and the production team. The insight generated by this project will guide the heads of the film industry to make informed decisions that will ensure the films produced align with the market demand. The insight will also be used by the production team in order to know which genres to capitalize on and which production styles to use. 

In conclusion, this project is very fundamental to Microsoft as it will provide important insight that will make their insertion into the film industry successful.

## Data Overview

Data is the most important part of the project since it's what will be used to provide insight and recommendations. The data used in this project comes from movie datasets from:
* Box Office - This dataset provides data on how much revenue movies earn through ticket sales.
* IMDB - This database contains data about the user ratings, reviews and production details. It ise used to generate feedback about a certain film
* Rotten Tomatoes - This database contains information about how well a movie was received. It is used to gauge a movie's overall quality in terms of user rating and criticism
* The MovieDB - This database contains information on ratings, reviews, trailers, and images.
* The Numbers - This database provides detailed information on box office performance, film production budgets, and financial aspects of the movie industry. It tracks the financial success of films and gives insights into their profitability, including revenue from domestic and international markets.

In [12]:
# Your code here - remember to use markdown cells for comments as well!
import pandas as pd
import csv
import gzip
basics = pd.read_csv('zippedData/imdb.title.basics.csv.gz', compression ='gzip')
ratings = pd.read_csv('zippedData/imdb.title.ratings.csv.gz', compression ='gzip')
gross = pd.read_csv('zippedData/bom.movie_gross.csv.gz', compression ='gzip')

In [3]:
with gzip.open('zippedData/imdb.title.basics.csv.gz', mode='rt', encoding='utf-8') as f:
    df = csv.DictReader(f)
    title = list(df)

In [4]:
with gzip.open('zippedData/imdb.title.ratings.csv.gz', mode='rt', encoding='utf-8') as f:
    df1 = csv.DictReader(f)
    ratings = list(df1)

In [5]:
with gzip.open('zippedData/bom.movie_gross.csv.gz', mode='rt', encoding='utf-8') as f:
    df = csv.DictReader(f)
    gross = list(df)

In [6]:
titles = [i['primary_title'] for i in title]

In [11]:
gross1 = []
for j in gross:
    if j['title'] in titles:
        gross1.append(j['title'])
len(gross1)

2606

In [53]:
ratings.head().sort_values(by='tconst')

       tconst  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21

In [54]:
gross.head().sort_values(by='foreign_gross', ascending=False)

,title,studio,domestic_gross,foreign_gross,year
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
0,Toy Story 3,BV,415000000.0,652000000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010